### PR TITLE
send hardware id type with each request

### PR DESCRIPTION
**Pull request by ahmednawar**
Please submit your PR against the `staging` branch.

@derrickstaten @aaustin 

cc @scott-branchio

### CODE REVIEW

**Comment by scott-branchio** [comment]
@ahmednawar is this ready to test?  is this something that should/can be added to the Android SDK...to keep them as close as possible?

**Comment by aaustin** [comment]
looks good to me 👍

**Comment by ahmednawar** [comment]
@scott-branchio yes, it is ready to test. As for Android, we need to check with @sojanpr about that

**Comment by sojanpr** [comment]
@scott-branchio Android only uses  device id or a generated UUID . So `is_harware_id_real` is enough

**Comment by scott-branchio** [comment]
@ahmednawar completed testing TestBed app 👍

**Pull request merged**
