### PR TITLE
add session_id and identity_id to debug

### PR DESCRIPTION
**Pull request by derrickstaten**
@Sarkar @dmitrig01

### CODE REVIEW

**Comment by dmitrig01** [comment]
is there any other device data we can send here?

**Comment by derrickstaten** [comment]
Yes, what else would you like?

**Comment by dmitrig01** [comment]
what do youh vae to offer?

**Comment by dmitrig01** [comment]
:+1:

**Comment by dmitrig01** [comment]
of course i don't really know what i'm doing

**Pull request merged**
