### PR TITLE
Readd initsession check

### PR DESCRIPTION
**Pull request by derrickstaten**
@danwalkowski @aaustin note that this purposefully includes one other commit (submitted in a different PR) so that I can ask a partner to test this.

### CODE REVIEW

**Comment by aaustin** [comment]
Isn't this a lot of what you had before?

**Comment by derrickstaten** [comment]
Yes, it's exactly what we had before. We should put this back in, as it prevents race conditions when initSession is in progress but not yet finished

**Comment by danwalkowski** [comment]
:+1:   this pr was blamed for the problems caused by the other pr that sometimes produced a nil sessionID

**Comment by danwalkowski** [comment]
:+1:

**Pull request merged**
