### PR TITLE
Add support for setting email subject when using BranchUniversalObject.

### PR DESCRIPTION
**Pull request by mikeantonelli**
This Pull Request will allow consumers to set the potential email subject line if Mail is selected from the share sheet presented for a BranchUniversalObject.

### CODE REVIEW

**Comment by mikeantonelli** [comment]
I checked out master and ran tests, it looks like the two tests that are failing also currently fail in master - might be related to https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/issues/193?

**Comment by danwalkowski** [comment]
Thanks Mike,
I will review it.

**Comment by derrickstaten** [comment]
@mikeantonelli thanks for submitting this! We're trying to keep this class pretty lightweight and not let it get bloated with a lot of methods (we're learning from other parts of our code base). We may instead refactor this to use a special key like `$email_subject` that can be set as a control parameter on the LinkProperties object. How does that sound?

**Comment by mikeantonelli** [comment]
I originally added a property on `BranchUniversalObject` and spoke with @aaustin over email about extending the existing `showShareSheet` API. It's a pretty simple refactor to make it a control param on `BranchLinkProperties`, sound good @aaustin?

**Comment by derrickstaten** [comment]
@mikeantonelli can you check out this branch? https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/tree/email-subject

Specifically, https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/blob/email-subject/Branch-SDK/Branch-SDK/BranchUniversalObject.m#L143-L150

**Comment by mikeantonelli** [comment]
Yep, exactly what I was thinking @derrickstaten - have you guys thought about using `FOUNDATION_EXPORT` instead of `extern`?

**Comment by derrickstaten** [comment]
@mikeantonelli convention more than anything is the reason we use `extern`. Do you think there are any tangible benefits to `FOUNDATION_EXPORT`? 

Also, I'm opening a PR with the code in that branch. Can you make sure it works as expected for you?

**Comment by derrickstaten** [comment]
I'm closing this for now, since we refactored in https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pull/245. Thanks for all the help here @mikeantonelli! We'll likely get this in as part of a release tomorrow.

**Pull request closed without merging**
