### PR TITLE
iOS deferred deep linking apns

### PR DESCRIPTION
**Pull request by derrickstaten**
@derrickstaten

still needs a bit of logic

### CODE REVIEW

**Comment by derrickstaten** [comment]
needs testing by @danwalkowski now

**Comment by derrickstaten** [comment]
Scenarios to test having push notifications received:
- [ ] app is not open and not backgrounded
- [ ] app is backgrounded
- [ ] app is already opened

other considerations:
- [ ] might be nice to have an "+is_push_notification" flag, but not a big deal for v1
- [ ] make sure no merge conflict with FB SDK code

**Comment by derrickstaten** [comment]
pair programmed together, so a bit weird for me to :+1:. @danwalkowski can you also leave a :+1:?

**Comment by danwalkowski** [comment]
:+1:

**Pull request merged**
