### PR TITLE
Fixes debug symbol generation issues with Xcode 7+

### PR DESCRIPTION
**Pull request by JackoPlane**
More info can be found on issue #191

### CODE REVIEW

**Comment by derrickstaten** [comment]
@JackoPlane thank you for submitting this. We've been unable to recreate the warnings on our end.

Can you verify that the warnings are no longer present using the framework on this branch: https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/tree/test-build

**Comment by JackoPlane** [comment]
@derrickstaten Issue is still present :-1:

**Comment by derrickstaten** [comment]
@JackoPlane if it isn't too much work, could you post an empty framework where these warnings occur? Or you can send to support@branchmetrics.io. Then once we can recreate, we can try to isolate the issue.

Also, you can compile the framework locally and test. In the SDK root directory, run `sh scripts/build_framework.sh`. This will allow you to toggle various flags, build, and see if the warnings are still present. I'd rather do this work for you -- if you're able to send over an empty framework with the warnings.

**Comment by JackoPlane** [comment]
@derrickstaten I've created a couple of sample projects trying to re-create the issue, I can't seem to get it to replicate. However on our main project, most people have the issue. I found the solution posted here: https://github.com/radialpoint/SupportKit/issues/53 Apparently other people have issues replicating it

**Comment by zac** [comment]
@derrickstaten Issue still here for me. You're following the steps to reproduce exactly in #191? Make sure you're using a computer other than your own for these tests...it might be a red-herring but the ModuleCache paths had your username hard-coded in them.

**Comment by JackoPlane** [comment]
@derrickstaten Any update on this?

**Comment by aaustin** [comment]
Hey @JackoPlane - We believe we found the issue. We're deploying a fix in the next update. Slated for this week some time.

**Comment by derrickstaten** [comment]
Fixed with https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pull/205

**Pull request closed without merging**
