### PR TITLE
Create Pull Request Template

### PR DESCRIPTION
**Pull request by ahmednawar**
Please submit your PR against the `staging` branch.

### CODE REVIEW

**Comment by shortstuffsushi** [comment]
Hi guys,

Looks like you're failing the build a lot lately. Since @qinweigong and I set this up, it seems I'm still listed as a contact, and can't seem to get myself out of it. Could you either fix the build, or remove me from the list of people who are notified, or both?

**Comment by ahmednawar** [comment]
@shortstuffsushi if you go to your [CircleCI account] (https://circleci.com/account) --> Notifications Tab. Do you see something similar to this screenshot?

screen shot 2016-03-28 at 5 01 07 pm

**Comment by shortstuffsushi** [comment]
I do indeed.

screen shot 2016-03-28 at 7 28 47 pm

I set that around the same time as I sent this message, but it would be nice to be removed entirely if possible. If not, hopefully this will suffice.

**Comment by ahmednawar** [comment]
Apparently I can't make you unfollow a certain project. This is done on the
user's side. If you can see the project in your list, you can unfollow the
project and you won't get notifications.

On Mon, Mar 28, 2016 at 5:29 PM, Graham Mueller <notifications@github.com>
wrote:

> I do indeed.
>
> [image: screen shot 2016-03-28 at 7 28 47 pm]
> <https://cloud.githubusercontent.com/assets/1016147/14094386/58d7781e-f51b-11e5-8db7-6dc03f4b64f7.png>
>
> I set that around the same time as I sent this message, but it would be
> nice to be removed entirely if possible. If not, hopefully this will
> suffice.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/BranchMetrics/iOS-Deferred-Deep-Linking-SDK/pull/325#issuecomment-202643293>
>



-- 
[image: Branch] <https://branch.io/?bmp=xink-sig>
Ahmed Nawar
Integrations Engineer
What is deep linking? <https://t.xink.io/Tracking/Index/Kg4AAGZBAADC6gkA0>
Check out our webinars <https://t.xink.io/Tracking/Index/Kw4AAGZBAADC6gkA0>

**Pull request merged**
