### PR TITLE
Fftl disabler

### PR DESCRIPTION
**Pull request by Sarkar**
to test:

[branch disableFourFingerTouchObserver] before calling initSession (just like setDebug).
in simulator, hold option, and long click. 

@danwalkowski @derrickstaten

### CODE REVIEW

**Comment by dmitrig01** [comment]
we can probably remove the four-finger touch entirely, since we've deprecated it on the dashboard/backend right?

**Comment by danwalkowski** [comment]
Seems straightforward.  :+1:

**Comment by derrickstaten** [comment]
@Sarkar I agree with Dmitri -- let's pull this entirely since we don't have it on the dashboard. Otherwise your code looks good :)

**Comment by Sarkar** [comment]
fair enough, i'll modify this to remove all code here! thanks @dmitrig01 @derrickstaten

**Comment by Sarkar** [comment]
@derrickstaten @danwalkowski updated - removed all traces of gestures

**Comment by derrickstaten** [comment]
@Sarkar i pulled out a bunch of files. Can you or @danwalkowski confirm that it still works on your machine? Works for me and all tests pass locally.

**Comment by derrickstaten** [comment]
@danwalkowski can you review? i deleted a lot of stuff so i want to make sure it still compiles

**Comment by Sarkar** [comment]
ill download locally and test as well

**Comment by Sarkar** [comment]
looks good to me after local testing. :+1:

**Pull request merged**
